#!/bin/sh
uci set network.wan.proto='static'
uci set network.wan.ipaddr='172.20.0.2'
uci set network.wan.netmask='255.255.255.0'
uci set network.wan.gateway='172.20.0.1'
uci commit network

# eth2 (QEMU user-netdev) konfigurieren
uci set network.qemu=interface
uci set network.qemu.ifname='eth2'
uci set network.qemu.proto='dhcp'
uci commit network

uci add network route
uci set network.@route[-1].interface='qemu'
uci set network.@route[-1].target='172.18.0.0'
uci set network.@route[-1].netmask='255.255.255.0'
uci set network.@route[-1].gateway='10.0.2.2'
uci commit network

uci add_list firewall.@zone[0].network='qemu'
uci commit firewall

chmod +x /usr/bin/firmware-proxy /etc/init.d/firmware-proxy
/etc/init.d/firmware-proxy enable
/etc/init.d/firmware-proxy start

(echo "2003"; echo "2003") | passwd root
