#!/bin/sh
uci -q delete network.lan.type
uci -q delete network.lan.ifname
uci set network.lan.device='eth1'
uci set network.lan.proto='static'
uci set network.lan.ipaddr='172.18.0.50'
uci set network.lan.netmask='255.255.255.0'

uci -q delete network.wan.ifname
uci set network.wan.device='eth0'
uci set network.wan.proto='static'
uci set network.wan.ipaddr='172.22.0.2'
uci set network.wan.netmask='255.255.255.0'
uci set network.wan.gateway='172.22.0.1'
uci commit network

# eth2 (QEMU user-netdev) fuer Host-Management konfigurieren
uci set network.qemu=interface
uci set network.qemu.device='eth2'
uci set network.qemu.proto='dhcp'
uci commit network

# Put qemu interface into LAN zone (input ACCEPT) so DNS requests from the
# forwarded side are accepted.
uci -q add_list firewall.lan.network='qemu' || uci -q delete firewall.qemu_zone
uci set firewall.qemu_zone=zone
uci set firewall.qemu_zone.name='qemu'
uci add_list firewall.qemu_zone.network='qemu'
uci set firewall.qemu_zone.input='REJECT'
uci set firewall.qemu_zone.output='ACCEPT'
uci set firewall.qemu_zone.forward='REJECT'

uci -q delete firewall.allow_ssh_wan
uci set firewall.allow_ssh_wan=rule
uci set firewall.allow_ssh_wan.name='Allow-SSH-WAN'
uci set firewall.allow_ssh_wan.src='wan'
uci set firewall.allow_ssh_wan.dest_port='22 2222'
uci set firewall.allow_ssh_wan.proto='tcp'
uci set firewall.allow_ssh_wan.target='ACCEPT'

uci -q delete firewall.allow_ssh_qemu
uci set firewall.allow_ssh_qemu=rule
uci set firewall.allow_ssh_qemu.name='Allow-SSH-QEMU'
uci set firewall.allow_ssh_qemu.src='qemu'
uci set firewall.allow_ssh_qemu.dest_port='22 2222'
uci set firewall.allow_ssh_qemu.proto='tcp'
uci set firewall.allow_ssh_qemu.target='ACCEPT'

uci -q delete firewall.allow_proxy_qemu
uci set firewall.allow_proxy_qemu=rule
uci set firewall.allow_proxy_qemu.name='Allow-Proxy-QEMU'
uci set firewall.allow_proxy_qemu.src='qemu'
uci set firewall.allow_proxy_qemu.dest_port='8080'
uci set firewall.allow_proxy_qemu.proto='tcp'
uci set firewall.allow_proxy_qemu.target='ACCEPT'
uci commit firewall

uci set dropbear.@dropbear[0].PasswordAuth='on'
uci set dropbear.@dropbear[0].RootPasswordAuth='on'
uci commit dropbear

chmod +x /usr/bin/firmware-proxy /etc/init.d/firmware-proxy
/etc/init.d/firmware-proxy enable
/etc/init.d/firmware-proxy start

chmod +x /etc/init.d/router-ssh
/etc/init.d/dropbear disable
/etc/init.d/router-ssh enable
/etc/init.d/router-ssh start

# Default to the legitimate update server. Attackers can change this at runtime
# via UCI on the OpenWrt guest.
uci add_list dhcp.@dnsmasq[0].interface='qemu'
uci set dhcp.@dnsmasq[0].nonwildcard='0'
uci set dhcp.@dnsmasq[0].localservice='0'
uci add_list dhcp.@dnsmasq[0].address='/update.cybics/172.18.0.9'
uci commit dhcp

(echo "2003"; echo "2003") | passwd root
