services:
  openwrt:
    build:
      context: .
      dockerfile: Dockerfile
    image: cybics-openwrt-router
    hostname: openwrt
    restart: "no"
    stdin_open: true
    tty: true
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - "2222:2222"
    networks:
      ext_ctf:
        ipv4_address: 172.22.0.2
      virt-cybics:
        ipv4_address: 172.18.0.50
    profiles:
      - firmware-update-environment
      - full

networks:
  ext_ctf:
    external: true
  virt-cybics:
    external: true
    name: virtual_virt-cybics